### ISSUE TITLE
Can I get some help with installation?

### ISSUE THREAD

**Issue by veronicamb** [iTaxoTools/ConcatenatorGui#5]
Hello, 

I'm trying to install ConcatenatorGui but I'm getting some errors that are not helpful with troubleshooting.

Here's what Im getting:
 Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyside6>=6.1.1 (from concatenator-gui==0.2.1)
  Using cached PySide6-6.6.1-cp38-abi3-macosx_11_0_universal2.whl.metadata (5.3 kB)
Collecting itaxotools-common==0.3.3 (from concatenator-gui==0.2.1)
  Using cached itaxotools_common-0.3.3-py3-none-any.whl.metadata (2.0 kB)
INFO: pip is looking at multiple versions of concatenator-gui to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement itaxotools-pygblocks (from concatenator-gui) (from versions: none)
ERROR: No matching distribution found for itaxotools-pygblocks

any help will be appreciated!

thank you

Veronica

**Comment by StefanPatman** [comment]
Hello Veronica. 

If you are using Windows or macOS, it might be simpler to use the [precompiled executables](https://github.com/iTaxoTools/ConcatenatorGui/releases/tag/v0.2.1).
If you want to install anyway, please keep reading.

The latest version of the tool depended on a private repository for [pygblocks](https://github.com/iTaxoTools/pygblocks).
I just made the repository public. The installation instructions as described in the README should now work again.
You will need to either clone the repository again, or pull the latest changes from the main branch.

Please notice that a new version is currently in development, which adds a trimming step among other things.
If you are looking for a stable commit (and not each latest change), commit 5171064ba should work nicely, 

```
git clone https://github.com/iTaxoTools/ConcatenatorGui.git
cd ConcatenatorGui
git checkout 5171064
pip install -e . -f packages.html
concatenator-gui
```

Sorry for the inconvenience. Please let me know if you encounter any other problems with the repository.

I hope this helps!

**Comment by veronicamb** [comment]
Hello Stefan,

Thank you so much! This is super helpful!

I'm now running Concatenator locally and it's working pretty well! What a nice little package!

I was wondering if you could recommend a version of Concatenator that I could use on our HPC? I'm thinking it'd be Release V0.2.0 for Linux, but I wanted to check with you.

thanks again!!

Veronica

**Comment by StefanPatman** [comment]
I cannot really recommend this, since Concatenator was not created with HPCs in mind, but it should run fine if high performance is not a priority!

Unfortunately, the v0.2.0 tag will not work out of the box, due to some breaking dependencies since it was released and how the dependency management was done at the time. I would suggest using either the latest available commit from the main branch, or the commit from my previous message.

**Comment by StefanPatman** [comment]
Tag [v0.3.2 ](https://github.com/iTaxoTools/ConcatenatorGui/tree/v0.3.2) now has frozen dependencies for `packages.html`, which should result in a much smoother installation.
